steps:
- name: "gcr.io/cloud-builders/npm"
  args: ['run',"build"]
  dir: 'client'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "client/clientAppEngine.yaml", "server/serverAppEngine.yaml"]
timeout: "1600s"